//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beispiel_02
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PersonenEntities9 : DbContext
    {
        public PersonenEntities9()
            : base("name=PersonenEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Sohn> Sohn { get; set; }
    
        public virtual ObjectResult<PERSONEN_LADEN_Result> PERSONEN_LADEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PERSONEN_LADEN_Result>("PERSONEN_LADEN");
        }
    
        public virtual ObjectResult<SoehneLesen_Result> SoehneLesen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SoehneLesen_Result>("SoehneLesen");
        }
    
        public virtual int SohnEinfuegen(Nullable<long> id, string ausweis, string name, Nullable<long> fK_Id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var ausweisParameter = ausweis != null ?
                new ObjectParameter("Ausweis", ausweis) :
                new ObjectParameter("Ausweis", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var fK_IdParameter = fK_Id.HasValue ?
                new ObjectParameter("FK_Id", fK_Id) :
                new ObjectParameter("FK_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SohnEinfuegen", idParameter, ausweisParameter, nameParameter, fK_IdParameter);
        }
    }
}
