//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beispiel_02
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sohn
    {
        public long ID { get; set; }
        [Display(Name = "Ausweis")]
        [Required(ErrorMessage = "Ausweis eingeben")]
        public string AUSWEIS { get; set; }
        public string NAME { get; set; }
        public long FK_ID_PERSON { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Sohn Sohn1 { get; set; }
        public virtual Sohn Sohn2 { get; set; }
    }
}
